//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Fxist.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_FORWARDINDEXDLG             103
#define IDR_MAINFRAME                   128
#define IDR_FxistTYPE                   129
#define IDD_DIALOG_OVERVIEW             130
#define IDD_DIALOG_DOCUMENTS            131
#define IDD_DIALOG_INDEXING             132
#define IDD_DIALOG_SEARCHING            133
#define IDD_DIALOG1                     135
#define IDD_DIALOG_INDEXMAINTAIN        135
#define IDD_DIALOG_PLAINPARSERPARAM     137
#define IDD_DIALOG_DIRCOLCFG            138
#define IDD_DIALOG_COLCFG               138
#define IDD_DIALOG2                     139
#define IDD_DIALOG_INDEXINGPROG         139
#define IDD_DIALOG_PLUGIN               140
#define IDD_DIALOG3                     142
#define IDD_DIALOG_CREATEFXCOL          142
#define IDD_DIALOG4                     143
#define IDD_DIALOG_LOGOPTION            143
#define IDD_DIALOG_LOG                  144
#define IDD_DIALOG_STOPFILE             145
#define IDB_BITMAP_LOGO                 147
#define IDD_DIALOG_SCHEMA               148
#define IDD_DIALOG_HMADVANCE            150
#define IDD_DIALOG_ANALYZER_OPTION      151
#define IDD_DIALOG5                     153
#define IDD_DIALOG_PARSER_OPTION        153
#define IDD_DIALOG6                     155
#define IDD_DIALOG_FIELDANALYZER        155
#define IDC_LIST_FIELD                  1001
#define IDC_STATIC_INAME                1002
#define IDC_STATIC_IVERSION             1003
#define IDC_STATIC_DOCNUM               1004
#define IDC_STATIC_FIELDNUM             1005
#define IDC_STATIC_WORDNUM              1006
#define IDC_STATIC_DELDOCNUM            1007
#define IDC_STATIC_PARSER               1008
#define IDC_STATIC_ANALYZER             1009
#define IDC_STATIC_DOCNUM2              1010
#define IDC_STATIC_LASTMODIFY           1011
#define IDC_GROUP11                     1012
#define IDC_STATIC11                    1013
#define IDC_GROUP53                     1013
#define IDC_STATIC_PLUGNAME             1014
#define IDC_EDIT1                       1015
#define IDC_EDIT_TVFIELD                1015
#define IDC_EDIT_FXCOLSRC               1015
#define IDC_EDIT_MERGEINDEX             1015
#define IDC_EDIT_SFSRC                  1015
#define IDC_EDIT_STOPFILE               1015
#define IDC_EDIT_DOCTAG                 1015
#define IDC_EDIT_GPR                    1015
#define IDC_EDIT_PARSERPARAM            1015
#define IDC_EDIT_DOCNO                  1016
#define IDC_EDIT_MERGEFILE              1016
#define IDC_EDIT_SFDST                  1016
#define IDC_EDIT_ALIAS                  1016
#define IDC_EDIT7                       1016
#define IDC_EDIT_GPP                    1016
#define IDC_STATIC_BARRELNUM            1017
#define IDC_EDIT_FIELDANALYZER          1017
#define IDC_EDIT_HLM_M                  1017
#define IDC_EDIT_TOPK                   1018
#define IDC_EDIT_FIELDBOOST             1018
#define IDC_EDIT_HLM_C                  1018
#define IDC_EDIT_LOGFILE                1019
#define IDC_EDIT_SEARCHMEM              1019
#define IDC_EDIT_HLM_S                  1019
#define IDC_EDIT_FIELDNAME              1020
#define IDC_STATIC_PLUGCAT              1021
#define IDC_EDIT4                       1022
#define IDC_LIST_BARRELS                1023
#define IDC_EDIT_INDEXDST               1024
#define IDC_STATIC_PLUGID               1025
#define IDC_SPIN1                       1026
#define IDC_SPIN_MINSIZE                1026
#define IDC_SPIN_GPR                    1026
#define IDC_SPIN_DOCNO                  1027
#define IDC_SPIN5                       1027
#define IDC_SPIN_GPP                    1027
#define IDC_STATIC12                    1028
#define IDC_SPIN_HLM_M                  1028
#define IDC_SPIN_INDEXMEM               1029
#define IDC_SPIN_HLM_C                  1029
#define IDC_SPIN_TOPK                   1030
#define IDC_SPIN_INDEXMEM2              1030
#define IDC_SPIN_CACHEDOCS              1030
#define IDC_SPIN8                       1030
#define IDC_SPIN_HLM_S                  1030
#define IDC_STATIC_PLUGCLSID            1031
#define IDC_SPIN_SEARCHMEM              1031
#define IDC_LIST1                       1032
#define IDC_LIST_TVFIELDS               1032
#define IDC_LIST_SCHEMA                 1032
#define IDC_LIST_DOCRESULT              1033
#define IDC_SPIN2                       1034
#define IDC_SPIN_MAXSIZE                1034
#define IDC_STATIC_CURBARREL            1035
#define IDC_LIST_BARRELS2               1036
#define IDC_SPIN_MAXBARRELS             1037
#define IDC_LIST_QUERYHITS              1038
#define IDC_LIST_MBARRELS               1039
#define IDC_LIST_PLUGIN                 1040
#define IDC_EDIT2                       1041
#define IDC_EDIT_MINSIZE                1041
#define IDC_EDIT_PARSER_FILED           1041
#define IDC_EDIT_QUERYWORD              1042
#define IDC_EDIT_MAXSIZE                1042
#define IDC_STATIC14                    1043
#define IDC_EDIT_QUERYEXP               1044
#define IDC_EDIT_FORWARDINDEX           1045
#define IDC_STATIC_PLUGENABLE           1046
#define IDC_EDIT3                       1047
#define IDC_EDIT_BEGINTAG               1047
#define IDC_EDIT_DF                     1048
#define IDC_EDIT_ENDTAG                 1048
#define IDC_LIST_BARRELS3               1049
#define IDC_LIST_MERGEINDEX             1050
#define IDC_EDIT_ANALYZERESULT          1051
#define IDC_BUTTON1                     1052
#define IDC_BUTTON_TVADD                1052
#define IDC_BUTTON_OPENARG              1052
#define IDC_BUTTON_FXCOLBROWSE          1052
#define IDC_BUTTON_MERGEBROWSE          1052
#define IDC_BUTTON_VIEWLOG              1052
#define IDC_BUTTON_SFSRCBROWSE          1052
#define IDC_BUTTON_SHOWLOG              1052
#define IDC_BUTTON_SCMODIFY             1052
#define IDC_BUTTON_FI_ADD               1052
#define IDC_BUTTON_WPREVDOC             1053
#define IDC_BUTTON_MERGEFILEBROWSE      1053
#define IDC_BUTTON_SFDSTBROWSE          1053
#define IDC_BUTTON_SCADD                1053
#define IDC_BUTTON_META_ADD             1053
#define IDC_BUTTON_ALLTORIGHT           1054
#define IDC_BUTTON_SCDEL                1054
#define IDC_BUTTON_STARTINDEX           1055
#define IDC_BUTTON_SETUP                1056
#define IDC_BUTTON2                     1057
#define IDC_BUTTON_TVMOD                1057
#define IDC_BUTTON_SAVEARG              1057
#define IDC_BUTTON_CREATE               1057
#define IDC_BUTTON_WNEXTDOC             1058
#define IDC_BUTTON_TVDEL                1058
#define IDC_BUTTON_SAVEASARG            1058
#define IDC_BUTTON_TORIGHT              1059
#define IDC_BUTTON_SETPARAM             1060
#define IDC_BUTTON_GETMORE              1061
#define IDC_BUTTON3                     1062
#define IDC_BUTTON_HMADVANCE            1062
#define IDC_BUTTON_WLASTDOC             1063
#define IDC_BUTTON_TOLEFT               1064
#define IDC_BUTTON_SETPARAM2            1065
#define IDC_BUTTON_COLSETPARAM          1066
#define IDC_BUTTON_COLSCHEMA            1066
#define IDC_BUTTON4                     1067
#define IDC_BUTTON_ANALYZE_OPTION       1067
#define IDC_BUTTON_WORDQUERY            1068
#define IDC_BUTTON_PARSER_OPTION        1068
#define IDC_BUTTON_ALLTOLEFT            1069
#define IDC_BUTTON5                     1070
#define IDC_BUTTON_DELDOC               1071
#define IDC_EDIT5                       1072
#define IDC_EDIT_MAXTERMS               1073
#define IDC_BUTTON_ADDINDEX             1074
#define IDC_BUTTON6                     1075
#define IDC_BUTTON_WDELALLDOCS          1076
#define IDC_SPIN3                       1077
#define IDC_SPIN_MAXTERMS               1078
#define IDC_BUTTON_DELINDEX             1079
#define IDC_BUTTON_DOCNOQUERY           1080
#define IDC_EDIT6                       1081
#define IDC_EDIT_FACTOR                 1082
#define IDC_BUTTON7                     1083
#define IDC_EDIT_FACTOR2                1083
#define IDC_EDIT_RATIO                  1083
#define IDC_BUTTON_MERGEINDEX           1084
#define IDC_EDIT_FACTOR3                1084
#define IDC_EDIT_DELNUM                 1084
#define IDC_BUTTON_WFIRSTDOC            1085
#define IDC_EDIT_MDELNUM                1085
#define IDC_SPIN4                       1086
#define IDC_SPIN_FACTOR                 1087
#define IDC_EDIT_TF                     1088
#define IDC_SPIN_FACTOR2                1088
#define IDC_SPIN_RATIO                  1088
#define IDC_BUTTON_DPREVDOC             1089
#define IDC_SPIN_FACTOR3                1089
#define IDC_SPIN_DELNUM                 1089
#define IDC_BUTTON_DNEXTDOC             1090
#define IDC_BUTTON_DLASTDOC             1091
#define IDC_BUTTON_DFIRSTDOC            1092
#define IDC_GROUP21                     1093
#define IDC_GROUP22                     1094
#define IDC_GROUP23                     1095
#define IDC_GROUP24                     1096
#define IDC_STATIC21                    1097
#define IDC_PROGRESS_MERGE              1097
#define IDC_STATIC22                    1098
#define IDC_RADIO_TVNO                  1098
#define IDC_STATIC23                    1099
#define IDC_CHECK1                      1099
#define IDC_CHECK_APPEND                1099
#define IDC_CHECK_MERGETOONE            1099
#define IDC_CHECK_SEARCHABLE            1099
#define IDC_STATIC24                    1100
#define IDC_RADIO_NOSPLITE              1100
#define IDC_STATIC25                    1101
#define IDC_PROGRESS1                   1101
#define IDC_PROGRESS_CREATE             1101
#define IDC_STATIC26                    1102
#define IDC_RADIO_RANDSPLITE            1102
#define IDC_RADIO_NOMERGE               1102
#define IDC_EDIT_CURDOCNO               1103
#define IDC_RADIO_TAGSPLITE             1103
#define IDC_COMBO1                      1104
#define IDC_RADIO_OPTIMIZE              1104
#define IDC_COMBO_SFANALYZE             1104
#define IDC_COMBO_SEARCHDEFFIELD        1104
#define IDC_COMBO_FIELDTYPE             1104
#define IDC_COMBO_INDEXER               1104
#define IDC_COMBO_STOPFILTER            1104
#define IDC_COMBO_PARSER_META           1104
#define IDC_COMBO_COLLECTION            1105
#define IDC_COMBO_STORE                 1105
#define IDC_COMBO_STEMMING              1105
#define IDC_COMBO5                      1105
#define IDC_COMBO_PARSER_GETMETA        1105
#define IDC_COMBO_TVFIELD               1106
#define IDC_CHECK_DELDOCOPT             1106
#define IDC_COMBO_INDEX                 1106
#define IDC_COMBO_STEMMING2             1106
#define IDC_COMBO_STEMMING_LANGUAGE     1106
#define IDC_EDIT_BOOST                  1107
#define IDC_LIST_LOG                    1107
#define IDC_COMBO_FORWARDINDEX          1107
#define IDC_COMBO2                      1108
#define IDC_STATIC_TVTIP                1108
#define IDC_COMBO_FIELDANALYZER         1108
#define IDC_COMBO_PARSER                1109
#define IDC_COMBO3                      1110
#define IDC_STATIC_EMAIL                1110
#define IDC_COMBO_SEARCH_ANALYZER       1111
#define IDC_STATIC_HOMEPAGE1            1111
#define IDC_COMBO4                      1112
#define IDC_STATIC_HOMEPAGE2            1112
#define IDC_COMBO_LOGLEVEL              1113
#define IDC_GROUP42                     1113
#define IDC_STATIC13                    1114
#define IDC_RADIO1                      1114
#define IDC_RADIO_WRITEMODE             1114
#define IDC_RADIO_HLM                   1114
#define IDC_COMBO_WANALYZER             1115
#define IDC_RADIO2                      1115
#define IDC_RADIO_READWRITEMODE         1115
#define IDC_RADIO_GP                    1115
#define IDC_COMBO_INDEXFIELD            1116
#define IDC_RADIO3                      1116
#define IDC_RADIO_APPENDMODE            1116
#define IDC_RADIO_LOG                   1116
#define IDC_EDIT_SOURCE                 1117
#define IDC_BUTTON_BROWSESRC            1118
#define IDC_BUTTON_INDEXDST             1119
#define IDC_COMBO_ANALYZER              1120
#define IDC_EDIT_MAXBARRELS             1121
#define IDC_RADIO5                      1121
#define IDC_BUTTON_SEARCH               1122
#define IDC_BUTTON_INDEXDST2            1122
#define IDC_BUTTON_STOPFILEBROWSE       1122
#define IDC_BUTTON_LOGBROWSE            1123
#define IDC_RADIO4                      1123
#define IDC_RADIO_READAPPENDMODE        1123
#define IDC_RADIO_GP_R                  1123
#define IDC_BUTTON_ANALYZER             1124
#define IDC_RADIO6                      1124
#define IDC_RADIO_RATIO                 1124
#define IDC_RADIO_GP_P                  1124
#define IDC_BUTTON_ANA_OPTION           1124
#define IDC_BUTTON_ANALYZE              1125
#define IDC_RADIO7                      1125
#define IDC_RADIO_DELNUM                1125
#define IDC_STATIC_TOTALHITS            1126
#define IDC_COMBO_LOGLEVEL2             1126
#define IDC_COMBO_INDEXINGLEVEL         1126
#define IDC_STATIC_RETNUMS              1127
#define IDC_RADIO_HLMMERGE              1127
#define IDC_LIST_INDEXINFO              1128
#define IDC_COMBO_SCHEMAINDEXINGLEVEL   1128
#define IDC_RADIO_FORCEGC               1128
#define IDC_LIST_INDEXLOG               1129
#define IDC_RADIO_MRATIO                1129
#define IDC_GROUP31                     1130
#define IDC_EDIT_MRATIO                 1130
#define IDC_GROUP32                     1131
#define IDC_RADIO_MDELNUM               1131
#define IDC_BUTTON8                     1132
#define IDC_SPIN_MDELNUM                1132
#define IDC_BUTTON_UNDELALL             1133
#define IDC_RADIO_MFORCEGC              1133
#define IDC_BUTTON_MERGEBARRELS         1134
#define IDC_RADIO_TOWINDOW              1135
#define IDC_RADIO_TOFILE                1136
#define IDC_GROUP54                     1136
#define IDC_GROUP41                     1137
#define IDC_STATIC51                    1137
#define IDC_RADIO_MERGE                 1138
#define IDC_RADIO_OPTMERGE              1139
#define IDC_RADIO_PARTMERGE             1140
#define IDC_CHECK_DELDOCS               1141
#define IDC_STATIC52                    1141
#define IDC_GROUP51                     1142
#define IDC_COMBO_PARSER_FI             1142
#define IDC_GROUP52                     1143
#define IDC_CHECK2                      1144
#define IDC_CHECK_AUTOOPEN              1145
#define IDC_CHECK_STORE                 1146
#define IDC_CHECK_AUTOOPENLOG           1146
#define IDC_CHECK_INDEX                 1147
#define IDC_CHECK_INDEXMODIFY           1148
#define IDC_CHECK_FORWARDINDEX          1149
#define IDC_RADIO_SEQUENCE              1150
#define IDC_RADIO_FREQ                  1151
#define IDC_RADIO_POSITION              1152
#define IDC_BUTTON_TVFIRSTDOC           1153
#define IDC_BUTTON_TVPREVDOC            1154
#define IDC_BUTTON_TVNEXTDOC            1155
#define IDC_BUTTON_TVLASTDOC            1156
#define IDC_BUTTON_TVQUERY              1157
#define IDC_EDIT_TVDOCNO                1158
#define IDC_SPIN_TVDOCNO                1159
#define IDC_GROUP71                     1160
#define IDC_STATIC71                    1161
#define IDC_STATIC72                    1162
#define IDC_STATIC73                    1163
#define IDC_STATIC74                    1164
#define IDC_STATIC75                    1165
#define IDC_PROGRESS_INDEXING           1166
#define IDC_EDIT_WANALYZER              1167
#define IDC_EDIT_MAXMEM                 1168
#define IDC_EDIT_MAXMEM2                1169
#define IDC_EDIT_CACHEDOCS              1169
#define ID_FILE_CLOSEINDEX              32772
#define ID_Menu                         32773
#define ID_FILE_INDEXING                32775
#define ID_TOOL_CREATESTOPFILE          32778
#define ID_TOOL_CREATEFIRTEXCOL         32779
#define ID_VIEW_LOGWINDOW               32781
#define ID_TOOL_LOGOPTION               32783

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         32784
#define _APS_NEXT_CONTROL_VALUE         1143
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
